-- Create drop statements for all tables in reverse order of creation
-- This ensures that foreign key constraints are not violated during deletion
CREATE OR REPLACE PROCEDURE drop_tables AS
BEGIN   
    EXECUTE IMMEDIATE 'DROP TABLE simptome_pacienti CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE prescriptii CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE diagnostice CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE rezultate_teste CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE consultatii CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE tulburari_personalitate CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE teste_psihologice CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE simptome CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE medicamente CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE specialisti CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE pacienti CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE specialitati CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE categorii_varsta CASCADE CONSTRAINTS';
END;

-- Execute the procedure to drop all tables
-- EXEC DROP_TABLES;